### PR TITLE
World and GUI

### PR DESCRIPTION
**Pull request by szimmer1**
Laid down the bricks for hooking up the GUI and the model. Made some architectural decisions, needs further discussion next week

### CODE REVIEW

**Comment by szimmer1** [comment]
Note: Still need to write Karma tests... maybe hold off on the merge until those are included

**Comment by camargo** [comment]
Looking good so far. The only class I am worried about is the GUI class. My original intention was for the Tracejs code (everything in src) to be interface agnostic. This way other programs could build different UIs on top of the code base if they wanted. Is there anyway to move that class out into another js file? We may have to talk about this more in person.

**Comment by szimmer1** [comment]
Got you. The way I built it does create a dependency for GUI. We could separate GUI into the /js directory and make calls from GUI->World and not the other way around. That way, World's only dependencies are the source files

**Comment by camargo** [comment]
Yes I like that idea a lot

**Comment by szimmer1** [comment]
Ready to merge son

**Comment by camargo** [comment]
Almost.. I added the Primitives file yesterday to reflect the file layout of the book source. Can you factor this into your commit? Also why are we adding these files to Karma:

'src/js/Tracers/_Tracer.js',
'src/js/GeometricObjects/_GeometricObject.js'

Shouldn't the star patterns take care of these?

**Comment by szimmer1** [comment]
I added those because Karma was complaining that it wasn't finding the base classes before they get referenced in Sphere and SimpleSphere. 

Those changes are to ensure they get loaded first. It fixed the issue.

**Comment by camargo** [comment]
Ah okay so it's a dependency thing that's fine. Just make sure you have the Primitives files now in the commit and we should be good. Why are you adding an underscore before Sphere and GeometricObject?

**Comment by szimmer1** [comment]
The underscore makes it so the file comes first in the directory tree. But ya it's probably not needed with karma.config the way it is now

**Comment by szimmer1** [comment]
I added the Primitives folder. But removing the underscore breaks Karma! Turns out the underscore is needed. Pushing now

**Comment by camargo** [comment]
Interesting I'll look into it. Just make sure your gulpfile.js is also synced and I'll merge

**Comment by szimmer1** [comment]
Fixed

**Pull request merged**
