### PR TITLE
Almost there

### PR DESCRIPTION
**Pull request by majurg**
sry for the delay. 

I am having problems on how to approach this. I feel like I am close, I just don't really know how to translate the Tracer and SingleSphere to javascript very well. SingleSphere is supposed to extend tracer, which is fine. The problem I have comes from the trace_ray function in SingleSphere. It is supposed to check for a hit on a sphere, I just don't know the right way to reference the sphere in the function (look at pg 72 of the book). 

Any help would be appreciated

### CODE REVIEW

**Comment by camargo** [comment]
So World should have a member Sphere. Then use the world pointer to get the sphere and call hit  in the if statement. Does that make sense? When I get home I can give a more detailed answer.

**Comment by camargo** [comment]
Looks like you will have to add a Sphere to World

**Comment by szimmer1** [comment]
Yes I can confirm there is no sphere currently in World. When you add one, make sure it is being referenced correctly in World's renderScene() function.

Cheers, Shahar

**Comment by camargo** [comment]
How are we doing with this?

**Comment by majurg** [comment]
hey sorry if this is still a big block for everyone. I ran into hardware troubles over the weekend and ended up replacing my hard drive today. Will try to get it together and push something out soon. 

If it is a big block and would rather take over this task let me know

**Comment by majurg** [comment]
OK I've update the class. It seems like tests are passing and colors are being returned correctly. 

Let me know if I should make any code changes (it seems a little sloppy/weird in my mind)

**Comment by camargo** [comment]
Close. Take the var sphere = new Tracejs.Sphere(); out of the trace function. Then in the if statement do:

if (world_ptr.geo_sphere.hit(ray)) {
...
}

**Comment by majurg** [comment]
ok yea thats what I was trying to do before throwing that statement in there. I was running into a problem where the .hit() was trying to be accessed as a property and not a function. Ill keep tweaking it...

**Comment by majurg** [comment]
Alright, hopefully this is closer to correct. :D

**Pull request merged**
