### PR TITLE
Viewplane scales correctly

### PR DESCRIPTION
**Pull request by szimmer1**
Tracer now works for any view plane specified in GUI

### CODE REVIEW

**Comment by camargo** [comment]
So what was the problem?

**Comment by szimmer1** [comment]
There were a few haha. The main one was that I was changing canvas size via CSS but not changing the height and width of the canvas DOM element.

Also I noticed that performance drops off steeply with view plane sizes greater than 500 or 600px. Excited to see how it does when the shaders and light source are added

Shahar

**Comment by camargo** [comment]
Haha this will be interesting. We are not even ray-tracing yet, just
ray-casting. When recursion gets into the mix I expect performance to
crawl. It's going to be a fun one.

**Comment by szimmer1** [comment]
Hardware acceleration is starting to make a lot of sense

**Comment by camargo** [comment]
Mhmmm. Let's see where we are after we have reflections and then assess the
damage. The nice thing is we can use the data from our classes to hardware
accelerate in the future if we decide to do that.

**Comment by szimmer1** [comment]
Yee. I've got some plans in store for the next sprint...

**Comment by camargo** [comment]
Ok keep me posted. Just keep in mind I want to hold off on any hardware
stuff for now tho just cause I think it will make the project far more
complex. We need to focus on getting nice things on the screen first.. Then
later speed if we have time.

**Comment by szimmer1** [comment]
For sure, I don't know anything about hardware and am not planning on learning too much in this class. I mean to have a more responsive user interface

**Comment by camargo** [comment]
O excellent - I really like what we have so far. I was thinking you were
gonna put it on the gpu haha:) which I am all for... Eventually.

**Pull request merged**
