### PR TITLE
Sprint2 GUI

### PR DESCRIPTION
**Pull request by szimmer1**
Note : Tests aren't working yet, just opening pull request for code review

### CODE REVIEW

**Comment by camargo** [comment]
Looks good to me. Let me know when all the tests pass and I'll merge.

**Comment by szimmer1** [comment]
Tests are working but let me add camera UI just to finish up the Sprint 2 stuff

By the way, colors are acting strangely for everything... lights, objects, background... not sure what it is still but I'm looking into it

**Comment by camargo** [comment]
Hmm what do you mean strangely?

**Comment by szimmer1** [comment]
for geometric objects, all of them are initially green (set in by ), and changing the color doesn't do anything. This is probably a UI problem
for lights, changing color from the initial RGB(1,1,1) causes the object to either go dark or full white
for background color, changing the color usually causes it to go full white 

RGBColor Tests are on point, so I'm guessing it's the UI. I've debugged it quite thoroughly though, and can't find the problem. Could you check it out if you have time today?

**Comment by camargo** [comment]
Hmm how much are you changing the color by? 
They should be changed on increments from 0-1. They are then scaled by 255 in the tracer.

**Comment by szimmer1** [comment]
Oh haha. I had no idea that was happening, i was passing in RGB values 0-255. 

You can go ahead and merge this branch, the color changes will be in a different one

**Pull request merged**
